// Debe coincidir exactamente con el enum Rol de backend/prisma/schema.prisma.
export const ROLES = [
  "director_general",
  "encargado_sistemas",
  "gerente_tecnico_produccion",
  "asistente_tecnico_produccion",
  "supervisor_huerta",
  "ayudante_supervisor",
  "regador",
  "gerente_mantenimiento",
  "mecanico",
  "supervisor_cosecha",
  "supervisor_empaque",
  "encargado_cosecha_empaque",
  "gerente_logistica",
  "recursos_humanos",
  "encargado_nominas",
  "gerente_administrativo",
  "contador",
  "asistente_administrativo",
  "encargado_compras",
  "encargado_bodega",
  "bodeguista",
  "auditor",
] as const;
